dist: xenial
language: python
python:
 - 3.8

install:
  - pip install --upgrade pip
  - pip install poetry
  - pip install papermill
  # tomli missing poetry dependency?
  - pip install tomli
  - poetry update
  - poetry install -E all

jobs:
  - script:
    - pytest tests
  - script:
    # Currently checks that each notebook can run, but not its output
    - cd tests && bash check_notebooks.sh
