dist: xenial
language: python
python:
 - 3.8

install:
  - pip install --upgrade pip
  - pip install poetry
  - pip install papermill
  - poetry install

jobs:
  - script:
    - pytest tests
  - script:
    - cd notebooks && papermill "Tutorial 1a - Overview and an example analysis.ipynb"
