[tool.black]
line-length = 79

[tool.poetry]
name = "visualising-data-profiles"
packages = [{ include = "pace" }]
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
bokeh = ">=2.3"
numpy = ">=1.21"
pandas = ">=1.3"
scipy = ">=1.7"
numexpr = ">=2.7"
Bottleneck = ">=1.3"
pydantic = ">=1.8"

[tool.poetry.dev-dependencies]
notebook = "^6.4"
ipywidgets = ">=7.6"
matplotlib = ">=3.4.3"
sklearn = ">=0.20"
Sphinx = ">=4.3"
nbsphinx = ">=0.8"
pydata-sphinx-theme = ">=0.7"
pytest = ">=6.2"
psycopg2 = ">=2.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
