[tool.black]
line-length = 79

[tool.poetry]
name = "visualising-data-profiles"
packages = [{ include = "pace" }]
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
notebook = "^6.4"
bokeh = "^2.3"
numpy = "^1.21"
pandas = "^1.3"
scipy = "^1.7"
ipywidgets = "^7.6"
pytest = "^6.2.4"
numexpr = "^2.7.3"
Bottleneck = "^1.3.2"
pydantic = "^1.8.2"
matplotlib = "^3.4.3"
sklearn = "^0.0"
psycopg2 = "^2.9.1"
Sphinx = "^4.3.0"
nbsphinx = "^0.8.7"
pydata-sphinx-theme = "^0.7.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
