# An example YAML file

dataset:
  num_rows:
    - 10
  num_cols:
    - 5
  intersections:
    - 10
  datatype:
    - str
    # - float
  
seed:
    - 92846593

patterns:
  - monotone
  # - general

output:
  filename: tmp_tech_eval_results
