name: Python Package

on:
  push:
    branches: [ master, gh-workflow ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.7, 3.8]
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install papermill
        poetry update
        poetry install -E all

    - name: Run tests
      run: |
        pip install pytest
        pytest

    - name: Run notebooks
      run: |
        cd tests && bash check_notebooks.sh
